---

- name: Install common needed packages for IRMA
  apt:
    name: ['vim', 'aria2', 'git', 'python-dev', 'python3-dev',
           'unzip', 'make', 'python-setuptools', 'python3-setuptools',
           'build-essential', 'libssl-dev', 'cmake', 'libz-dev',
           'libffi-dev', 'psmisc', 'acl']
    state: present

# Install python-pip (cause the debian version is only 1.1)
- name: Downloading script get-pip.py
  get_url:
    url: "{{ pip_python2_url }}"
    dest: '/tmp'

- name: Installing pip for python2
  command: python get-pip.py
  args:
     chdir: '/tmp'

- name: Installing pip for python3
  command: python3 get-pip.py
  args:
   chdir: '/tmp'

# Install virtualenv
- name: Install virtualenv with pip
  pip:
    name: virtualenv
    state: present
    executable: pip3
