---

- name: Install locales variables forwarded by the SSH connection
  locale_gen:
    name: "{{ item.value }}"
    state: present
  with_dict: "{{ ansible_env|default({}) }}"
  when: ansible_env and (item.key.find("LANG") != -1 or item.key.find("LC_") != -1) and item.value != "C"

- name: Add a script to install automagically locales when missing
  copy:
    src: generate-locale.sh
    dest: /etc/profile.d/generate-locale.sh
    owner: root
    group: root
    mode: 0644
