test_routes = {
    "/scans": ["GET", "POST"],
    "/probes": ["GET"],
    "/scans/<scanid>": ["GET"],
    "/scans/<scanid>/files": ["POST"],
    "/scans/<scanid>/launch": ["POST"],
    "/scans/<scanid>/cancel": ["POST"],
    "/scans/<scanid>/results": ["GET"],
    "/results/<resultid>": ["GET"],
    "/tags": ["GET", "POST"],
    "/files": ["GET"],
    "/files/<sha256>": ["GET"],
    "/files/<sha256>/tags/<tagid>/add": ["GET"],
    "/files/<sha256>/tags/<tagid>/remove": ["GET"],
}
