"""empty message

Revision ID: 960de2c5749e
Revises: 801a4e6b3262
Create Date: 2018-05-22 15:47:51.455514

"""

# revision identifiers, used by Alembic.
revision = '960de2c5749e'
down_revision = '801a4e6b3262'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irma_fileKiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('submitter_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['irma_fileExt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('irma_file', 'size',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('irma_file', 'size',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_table('irma_fileKiosk')
    # ### end Alembic commands ###
