---

- name: Common tasks to execute on all servers
  hosts: all
  sudo: yes
  pre_tasks:
    # Run the equivalent of "apt-get update" as a separate step
    - name: Ensure that APT cache is up to date
      apt: update_cache=yes
    - name: Install Uncomplicated Firewall software
      apt: pkg=ufw state=present
    - name: Open OpenSSH port
      ufw: rule=allow port=ssh
    - name: Close all ports for Prod server
      ufw: state=enabled policy=deny
      when: vagrant|default(False) == False
  roles:
    - { role: mivok0.users, tags: 'users' }
    - { role: quarkslab.irma_provisioning_common, tags: 'common' }
    - { role: franklinkim.sudo, tags: 'sudo' }
    - { role: Ansibles.openssh, tags: 'openssh' }


- name: Frontend provisioning
  hosts: frontend
  sudo: yes
  roles:
    - { role: mivok0.users, tags: 'users', users: "{{ frontend_users }}" }
    - { role: quarkslab.nodejs, tags: 'nodejs' }
    - { role: gdamjan.uwsgi, tags: 'uwsgi' }
    - { role: Stouts.mongodb, tags: 'mongodb' }
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_frontend }}" }
    - { role: quarkslab.irma_provisioning_frontend, tags: 'frontend' }
    - { role: jdauphant.nginx, tags: 'nginx' }
  post_tasks:
    - name: Open Webserver port
      ufw: rule=allow port=80
    - name: Open OpenSSL port
      ufw: rule=allow port=443
      when: frontend_openssl|default(False) == True


- name: Brain provisioning
  hosts: brain
  sudo: yes
  roles:
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_brain }}" }
    - { role: Mayeu.RabbitMQ, tags: 'rabbitmq' }
    - { role: quarkslab.pureftpd, tags: 'pureftpd' }
    - { role: quarkslab.irma_provisioning_brain, tags: 'brain' }


- name: Probe provisioning
  hosts: probe
  sudo: yes
  roles:
    - { role: quarkslab.irma_provisioning_probe, tags: 'probe' }
    - { role: quarkslab.supervisor, tags: 'supervisor', supervisor_programs: "{{ supervisor_programs_probe }}" }


# Antivirus section
- name: ClamAV provisioning
  hosts: clamav
  sudo: yes
  roles:
    - { role: quarkslab.clamav, tags: 'clamav' }

- name: ComodoCAVL provisioning
  hosts: comodo
  sudo: yes
  roles:
    - { role: quarkslab.comodo_cavl, tags: 'comodo' }

- name: McAfee VSCL provisioning
  hosts: mcafee
  sudo: yes
  roles:
    - { role: quarkslab.mcafee_vscl, tags: 'mcafee_vscl' }

- name: StaticAnalyzer provisioning
  hosts: static-analyzer
  sudo: yes
  roles:
    - { role: quarkslab.static_analyzer, tags: 'static-analyzer' }

# vim: sw=2
