---
# Variables used by Vagrantfile are defined here

servers:
  - name: frontend.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.30
    hostname: frontend.irma
    cpus: 2
    memory: 2048
    shares:
      - share_from: ../irma-frontend
        share_to: /var/www/prod.project.local/current
        share_user: www-data
        share_group: www-data
        share_exclude:
          - .git/
          - venv/
          - web/dist
          - web/node_modules
          - app/components
  - name: brain.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.31
    hostname: brain.irma
    cpus: 2
    memory: 2048
    shares:
      - share_from: ../irma-brain
        share_to: /opt/irma/irma-brain/current
        share_user: irma
        share_group: irma
        share_exclude:
          - .git/
          - venv/
          - db/
  - name: clamav.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.32
    hostname: clamav.irma
    shares:
      - share_from: ../irma-probe
        share_to: /opt/irma/irma-probe/current
        share_user: irma
        share_group: irma
        share_exclude:
          - .git/
          - venv/
  - name: comodo.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.33
    hostname: comodo.irma
    shares:
      - share_from: ../irma-probe
        share_to: /opt/irma/irma-probe/current
        share_user: irma
        share_group: irma
        share_exclude:
          - .git/
          - venv/
  - name: mcafee.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.34
    hostname: mcafee.irma
    shares:
      - share_from: ../irma-probe
        share_to: /opt/irma/irma-probe/current
        share_user: irma
        share_group: irma
        share_exclude:
          - .git/
          - venv/
  - name: static-analyzer.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.35
    hostname: static-analyzer.irma
    shares:
      - share_from: ../irma-probe
        share_to: /opt/irma/irma-probe/current
        share_user: irma
        share_group: irma
        share_exclude:
          - .git/
          - venv/
  - name: virustotal.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.36
    hostname: virustotal.irma
    shares:
      - share_from: ../irma-probe
        share_to: /opt/irma/irma-probe/current
        share_user: irma
        share_group: irma
        share_exclude:
          - .git/
          - venv/


ansible_config:
  extra_vars:
    vagrant: true
    vagrant_share: true
  groups:
    frontend:
      - frontend.irma
    brain:
      - brain.irma
    clamav:
      - clamav.irma
    comodo:
      - comodo.irma
    mcafee:
      - mcafee.irma
    static-analyzer:
      - static-analyzer.irma
    virustotal:
      - virustotal.irma
    "probe:children":
      - clamav
      - comodo
      - mcafee
      - static-analyzer
      - virustotal
