---
# Variables used by Vagrantfile are defined here

servers:
  - name: frontend.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.30
    hostname: frontend.irma
    cpus: 2
    memory: 2048
  - name: brain.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.31
    hostname: brain.irma
    cpus: 2
    memory: 2048
  - name: clamav.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.32
    hostname: clamav.irma
  - name: comodo.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.33
    hostname: comodo.irma
  - name: mcafee.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.34
    hostname: mcafee.irma
  - name: static-analyzer.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.35
    hostname: static-analyzer.irma
  - name: virustotal.irma
    box: quarkslab/debian-7.7-amd64
    ip: 172.16.1.36
    hostname: virustotal.irma


ansible_config:
  extra_vars:
    vagrant: true
  groups:
    frontend:
      - frontend.irma
    brain:
      - brain.irma
    clamav:
      - clamav.irma
    comodo:
      - comodo.irma
    mcafee:
      - mcafee.irma
    static-analyzer:
      - static-analyzer.irma
    virustotal:
      - virustotal.irma
    "probe:children":
      - clamav
      - comodo
      - mcafee
      - virustotal
      - static-analyzer
