---
# Variables used by Vagrantfile are defined here

servers:
  - name: frontend.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.30
    hostname: frontend.irma
    cpus: 2
    memory: 2048
  - name: brain.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.31
    hostname: brain.irma
    cpus: 2
    memory: 2048
  - name: avs-linux.irma
    box: quarkslab/debian-7.7-amd64
    box_version: 1.0.1
    ip: 172.16.1.32
    hostname: avs-linux.irma
    cpus: 2
    memory: 2048


ansible_config:
  extra_vars:
    vagrant: true
  groups:
    frontend:
      - frontend.irma
    brain:
      - brain.irma
    clamav:
      - avs-linux.irma
    comodo:
      - avs-linux.irma
    mcafee:
      - avs-linux.irma
    static-analyzer:
      - avs-linux.irma
    virustotal:
      - avs-linux.irma
    avg:
      - avs-linux.irma
    "probe:children":
      - clamav
      - comodo
      - mcafee
      - virustotal
      - static-analyzer
      - avg
