---

## Global variables
nginx_sites:
  irma-demo:
    - listen 80 default_server
    - listen [::]:80 default_server ipv6only=on
    - client_max_body_size 100m
    - location ~ /\.ht {
        deny all;
      }
    - location /api {
        include uwsgi_params;
        rewrite ^/api/(.+) /$1 break;
        uwsgi_pass 127.0.0.1:8081;
      }
    - location /swagger {
        alias {{ frontend_install_dir }}/swagger/ui;
        index index.html;
      }
    - location /docs {
        rewrite ^/docs/(.+) /$1 break;
        expires -1;
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        root {{ frontend_install_dir }}/docs/_build/html;
        try_files $uri $uri/ /index.html =404;
      }
    - location / {
        expires -1;
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        root {{ frontend_install_dir }}/web/dist;
        try_files $uri $uri/ /index.html =404;
      }
    - error_log {{ nginx_log_dir }}/irma-demo.error.log
    - access_log {{ nginx_log_dir }}/irma-demo.access.log

# vim: sw=2
