---

hostname: "irma-frontend.local"

# IRMA Configuration
web_ui_api_url: "http://api.{{hostname}}/v1.1"


# Nginx role
nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP $remote_addr
    - proxy_set_header Host $http_host
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
    - proxy_set_header X-NginX-Proxy true
    - proxy_redirect off
    - proxy_http_version 1.1
    - proxy_set_header Upgrade $http_upgrade
    - proxy_set_header Connection "upgrade"
  gzip:
    - gzip on
    - gzip_disable "msie6"
    - gzip_comp_level 6
    - gzip_buffers 16 8k
    - gzip_http_version 1.1
    - gzip_types text/plain text/css application/json application/x-javascript text/javascript application/javascript
  http:
    - server_names_hash_bucket_size 64

nginx_remove_sites: ["default"]

nginx_sites:
  irma-api:
    - listen 80 default
    - listen [::]:80 ipv6only=on
    - server_name api.{{hostname}}
    - client_max_body_size 100m
    - location ~ /\.ht {
        deny all;
      }
    - location / {
        if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' '*';
           add_header 'Access-Control-Allow-Credentials' 'true';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With';
           add_header 'Access-Control-Max-Age' 1728000;
           add_header 'Content-Type' 'text/plain charset=UTF-8';
           add_header 'Content-Length' 0;
           return 204;
        }
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With';
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:8081;
      }
    - location /swagger {
        alias {{frontend_install_dir}}/swagger/ui;
        index index.html;
      }
    - location /docs {
        rewrite ^/docs/(.+) /$1 break;
        expires -1;
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        root {{frontend_install_dir}}/docs/_build/html;
        try_files $uri $uri/ /index.html =404;
      }
    - error_log {{nginx_log_dir}}/api.{{hostname}}.error.log
    - access_log {{nginx_log_dir}}/api.{{hostname}}.access.log
  irma-web-ui:
    - listen 80
    - listen [::]:80
    - server_name {{hostname}} www.{{hostname}}
    - client_max_body_size 100m
    - location ~ /\.ht {
        deny all;
      }
    - location / {
        expires -1;
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
        root {{web_ui_install_dir}}/dist;
        try_files $uri $uri/ /index.html =404;
      }
    - error_log {{nginx_log_dir}}/{{hostname}}.error.log
    - access_log {{nginx_log_dir}}/{{hostname}}.access.log
