---
# Variables used by Vagrantfile are defined here

servers:
  - name: allinone
    box: quarkslab/debian-8.6.0-amd64
    ip: 172.16.1.30
    hostname: brain.irma
    cpus: 2
    cpuexecutioncap: 100
    memory: 2048
    shares:
      - share_from: ../web-ui
        share_to: /opt/irma/irma-web-ui/current
        share_exclude:
          - .git/
          - dist
          - node_modules
          - components
      - share_from: ../frontend
        share_to: /opt/irma/irma-frontend/current
        share_exclude:
          - .git/
          - venv/
      - share_from: ../brain
        share_to: /opt/irma/irma-brain/current
        share_exclude:
          - .git/
          - venv/
          - db/
      - share_from: ../probe
        share_to: /opt/irma/irma-probe/current
        share_exclude:
          - .git/
          - venv/

ansible_config:
  extra_vars:
    vagrant: true
    vagrant_share: true
    irma_environment: development
  groups:
    web-ui:
      - allinone
    frontend:
      - allinone
    brain:
      - allinone
    comodo:
      - allinone
    trid:
      - allinone
    "probe:children":
      - comodo
      - trid
