---
# Variables used by Vagrantfile are defined here

servers:
  - name: frontend
    box: quarkslab/debian-8.6.0-amd64
    ip: 172.16.1.30
    hostname: irma-frontend.local
    aliases:
      - api.irma-frontend.local
    cpus: 2
    cpuexecutioncap: 100
    memory: 2048
  - name: brain
    box: quarkslab/debian-8.6.0-amd64
    ip: 172.16.1.31
    hostname: brain.irma
    cpus: 2
    cpuexecutioncap: 100
    memory: 2048
  - name: avs-linux
    box: quarkslab/debian-8.6.0-amd64
    ip: 172.16.1.32
    hostname: avs-linux.irma
    cpus: 2
    cpuexecutioncap: 100
    memory: 2048
  # - name: mcafee-win
  #   box: eval-win10-enterprise
  #   ip: 172.16.1.33
  #   hostname: mcafee-win.irma
  #   cpus: 2
  #   cpuexecutioncap: 100
  #   memory: 2048
  #   windows: true

libvirt_config:
  driver: kvm
  # connect_via_ssh: true
  # host:
  # username:
  # storage_pool_name:
  # id_ssh_key_file:

ansible_config:
  extra_vars:
    vagrant: true
  groups:
    web-ui:
      - frontend
    frontend:
      - frontend
    brain:
      - brain
    clamav:
      - avs-linux
    comodo:
      - avs-linux
    mcafee:
      - avs-linux
    static-analyzer:
      - avs-linux
    virustotal:
      - avs-linux
    avg:
      - avs-linux
    bitdefender:
      - avs-linux
    escan:
      - avs-linux
    virusblokada:
      - avs-linux
    zoner:
      - avs-linux
    drweb:
      - avs-linux
    avast:
      - avs-linux
    fsecure:
      - avs-linux
    trid:
      - avs-linux
    sophos:
      - avs-linux
    mcafee-win:
      - mcafee-win
    "probe:children":
      - clamav
      - comodo
      - mcafee
      - virustotal
      - static-analyzer
      - avg
      - bitdefender
      - escan
      - virusblokada
      - zoner
      - drweb
      - avast
      - fsecure
      - trid
      - sophos
      - mcafee-win
    "windows:children":
      - mcafee-win
