import modules.antivirus.zoner.zoner
import modules.antivirus.fsecure.fsecure
import modules.antivirus.emsisoft_win.asquared_win
import modules.antivirus.kaspersky_win.kaspersky_win
import modules.antivirus.avast.avast
import modules.antivirus.interface
import modules.antivirus.drweb.drweb
import modules.antivirus.symantec_win.symantec_win
import modules.antivirus.gdata_win.gdata_win
import modules.antivirus.comodo.cavl
import modules.antivirus.mcafee.vscl
import modules.antivirus.mcafee_win.vscl
import modules.antivirus.base
import modules.antivirus.fprot.fprot
import modules.antivirus.sophos_win.sophos_win
import modules.antivirus.escan.escan
import modules.antivirus.sophos.sophos
import modules.antivirus.clamav.clam
import modules.antivirus.eset.eset_file_security
import modules.antivirus.kaspersky.kaspersky
import modules.antivirus.virusblokada.virusblokada
import modules.antivirus.bitdefender.bitdefender
import modules.antivirus.avg.avg
import modules.database.nsrl.nsrl
import modules.metadata.trid.trid
import modules.metadata.lief.lief_analyzer
import modules.metadata.pe_analyzer.pe
