---

- name: Kaspersky | Create temporary work dir
  file:
    path: "{{kaspersky_tmp_dir}}"
    state: directory

- name: Kaspersky | Download Package
  get_url:
    url: "{{ kaspersky_url}}"
    dest: "{{kaspersky_tmp_dir}}/kaspersky.deb"
  when: ansible_os_family == "Debian"

- name: Kaspersky | Run installer
  apt:
    deb: "{{kaspersky_tmp_dir}}/kaspersky.deb"
  become: yes

- name: Kaspersky | Remove temporary work dir
  file:
    path: "{{kaspersky_tmp_dir}}"
    state: absent
